// Framework signatures — declarative, and every detection carries its reason.
//
// ---------------------------------------------------------------------------
// WHY EVERY SIGNAL IS WEIGHTED RATHER THAN BOOLEAN
// ---------------------------------------------------------------------------
//
// Framework detection is guessing, and the useful question is not "did we
// guess?" but "how much would you bet on this guess, and on what basis?"
//
// A dependency entry is close to proof: `"next": "^14"` in package.json means
// somebody installed Next.js. A directory name is not: `app/` means Next's app
// router, or Rails, or nothing at all. A repository with a `pages/` folder and
// no `next` dependency is a static site, and reporting "Next.js detected"
// there sends a reviewer looking for `getServerSideProps` in a project that
// has never had any.
//
// So each signal carries a weight, detection sums them, and the result exposes
// both the confidence and the evidence list that produced it. A reader who
// disagrees with a detection can see exactly which signal caused it — which is
// the difference between a heuristic you can correct and one you must trust.
//
// Thresholds: >= 3 high, >= 2 medium, 1 low — and one cap on top, because the
// sum alone gets this wrong. A detection built ONLY from directory names never
// rises above low, however many match: accumulating weak evidence does not
// make it strong, and two conventional folder names summing to "medium" is
// precisely how a static site gets announced as Next.js.
//
// A lone weak signal is still reported rather than suppressed, because "we saw
// a Rails-shaped layout and no Gemfile" is worth showing to someone deciding
// whether the scan looked in the right places.

/**
 * Signal kinds and what they are worth.
 *
 *   dependency  a name in a manifest's dependency map          3  (near-proof)
 *   configFile  a framework's own config file at any depth     3  (near-proof)
 *   markerFile  a file the framework's tooling generates       2
 *   directory   a conventional directory layout                1  (weak alone)
 */
const WEIGHT = Object.freeze({ dependency: 3, configFile: 3, markerFile: 2, directory: 1 });

export const FRAMEWORKS = Object.freeze([
  // ---- JavaScript / TypeScript -------------------------------------------
  {
    id: "nextjs", name: "Next.js", language: "javascript",
    dependency: ["next"],
    configFile: ["next.config.js", "next.config.mjs", "next.config.ts"],
    // `pages` and `app` are Next conventions AND Rails/Nuxt conventions, so
    // they are weight-1 and can never reach "high" on their own.
    directory: ["pages", "app"],
  },
  {
    id: "react", name: "React", language: "javascript",
    dependency: ["react"],
    // .jsx/.tsx presence is handled by the caller as an extension signal.
  },
  {
    id: "vue", name: "Vue", language: "javascript",
    dependency: ["vue"],
    configFile: ["vue.config.js"],
  },
  {
    id: "nuxt", name: "Nuxt", language: "javascript",
    dependency: ["nuxt", "nuxt3"],
    configFile: ["nuxt.config.js", "nuxt.config.ts"],
  },
  {
    id: "angular", name: "Angular", language: "typescript",
    dependency: ["@angular/core"],
    configFile: ["angular.json"],
  },
  {
    id: "svelte", name: "Svelte / SvelteKit", language: "javascript",
    dependency: ["svelte", "@sveltejs/kit"],
    configFile: ["svelte.config.js"],
  },
  {
    id: "remix", name: "Remix", language: "javascript",
    dependency: ["@remix-run/node", "@remix-run/react", "remix"],
    configFile: ["remix.config.js"],
  },
  {
    id: "express", name: "Express", language: "javascript",
    dependency: ["express"],
  },
  {
    id: "nestjs", name: "NestJS", language: "typescript",
    dependency: ["@nestjs/core"],
    configFile: ["nest-cli.json"],
  },
  {
    id: "fastify", name: "Fastify", language: "javascript",
    dependency: ["fastify"],
  },

  // ---- Python ------------------------------------------------------------
  {
    id: "django", name: "Django", language: "python",
    dependency: ["django", "Django"],
    // manage.py is generated by django-admin and is close to conclusive.
    markerFile: ["manage.py"],
    configFile: ["settings.py", "wsgi.py", "asgi.py"],
  },
  {
    id: "flask", name: "Flask", language: "python",
    dependency: ["flask", "Flask"],
  },
  {
    id: "fastapi", name: "FastAPI", language: "python",
    dependency: ["fastapi"],
  },

  // ---- Ruby --------------------------------------------------------------
  {
    id: "rails", name: "Ruby on Rails", language: "ruby",
    dependency: ["rails"],
    configFile: ["config/routes.rb", "config/application.rb"],
    directory: ["app/controllers", "app/models"],
  },
  {
    id: "sinatra", name: "Sinatra", language: "ruby",
    dependency: ["sinatra"],
  },

  // ---- JVM ---------------------------------------------------------------
  {
    id: "spring", name: "Spring / Spring Boot", language: "java",
    dependency: ["spring-boot-starter", "spring-boot-starter-web", "org.springframework.boot", "spring-core"],
    configFile: ["application.properties", "application.yml", "application.yaml"],
  },

  // ---- Go ----------------------------------------------------------------
  { id: "gin",   name: "Gin",   language: "go", dependency: ["github.com/gin-gonic/gin"] },
  { id: "echo",  name: "Echo",  language: "go", dependency: ["github.com/labstack/echo"] },
  { id: "fiber", name: "Fiber", language: "go", dependency: ["github.com/gofiber/fiber"] },
  {
    id: "nethttp", name: "net/http service", language: "go",
    // Standard library, so there is no dependency entry to find. The import
    // is the only signal, and the caller supplies it from sampled content.
    importPattern: ["net/http"],
  },

  // ---- PHP ---------------------------------------------------------------
  {
    id: "laravel", name: "Laravel", language: "php",
    dependency: ["laravel/framework"],
    markerFile: ["artisan"],
  },
  {
    id: "symfony", name: "Symfony", language: "php",
    dependency: ["symfony/framework-bundle", "symfony/symfony"],
  },

  // ---- .NET --------------------------------------------------------------
  {
    id: "aspnet", name: "ASP.NET Core", language: "csharp",
    dependency: ["Microsoft.AspNetCore.App", "Microsoft.AspNetCore"],
    configFile: ["appsettings.json"],
    markerFile: ["Program.cs", "Startup.cs"],
  },
]);

/**
 * Score to confidence, with a hard cap that the score alone cannot express.
 *
 * `strong` is true when at least one signal was something other than a
 * directory name. Without that cap, two weight-1 directories sum to 2 and
 * report "medium" — which is how a static site with `pages/` and `app/` gets
 * announced as Next.js. Accumulating weak evidence does not make it strong:
 * a hundred directory matches still do not show that anybody installed the
 * framework, so directory-only detections are pinned at low however many fire.
 */
const CONFIDENCE_FOR = (score, strong) => {
  if (!strong) return "low";
  return score >= 3 ? "high" : score >= 2 ? "medium" : "low";
};

/**
 * Detect frameworks from a repository's shape.
 *
 * Pure: every input is supplied by the caller, so this is testable without a
 * repository, a network, or a filesystem.
 *
 *   paths        every non-ignored path in the repository
 *   dependencies package/module names gathered from manifests, lowercased
 *   extensions   Set of extensions present, for the React/.jsx signal
 *   imports      import strings sampled from source, for stdlib frameworks
 */
export function detectFrameworks({ paths = [], dependencies = [], extensions = new Set(), imports = [] } = {}) {
  const lowerPaths = paths.map((p) => String(p).toLowerCase());
  const pathSet = new Set(lowerPaths);
  const deps = new Set(dependencies.map((d) => String(d).toLowerCase()));
  const importSet = new Set(imports.map((i) => String(i).toLowerCase()));

  const out = [];
  for (const fw of FRAMEWORKS) {
    let score = 0;
    // Whether any signal other than a directory name fired. See CONFIDENCE_FOR.
    let strong = false;
    const evidence = [];

    for (const dep of fw.dependency || []) {
      if (deps.has(dep.toLowerCase())) {
        score += WEIGHT.dependency;
        strong = true;
        evidence.push(`dependency: ${dep}`);
      }
    }
    for (const file of fw.configFile || []) {
      const hit = matchPath(lowerPaths, pathSet, file);
      if (hit) { score += WEIGHT.configFile; strong = true; evidence.push(hit); }
    }
    for (const file of fw.markerFile || []) {
      const hit = matchPath(lowerPaths, pathSet, file);
      if (hit) { score += WEIGHT.markerFile; strong = true; evidence.push(hit); }
    }
    for (const dir of fw.directory || []) {
      const d = dir.toLowerCase();
      const hit = lowerPaths.some((p) => p === d || p.startsWith(d + "/") || p.includes("/" + d + "/"));
      if (hit) { score += WEIGHT.directory; evidence.push(`directory: ${dir}/`); }
    }
    for (const imp of fw.importPattern || []) {
      if (importSet.has(imp.toLowerCase())) {
        score += WEIGHT.dependency;
        strong = true;
        evidence.push(`import: ${imp}`);
      }
    }

    // React earns a second signal from .jsx/.tsx, but only alongside the
    // dependency — a .jsx file with no react dependency is Preact, Solid, or
    // somebody's build artifact, and claiming React from the extension alone
    // is the classic false positive this weighting exists to prevent.
    if (fw.id === "react" && score > 0 && (extensions.has("jsx") || extensions.has("tsx"))) {
      score += WEIGHT.markerFile;
      evidence.push("jsx/tsx files present");
    }

    if (score > 0) {
      out.push({
        name: fw.name,
        language: fw.language,
        confidence: CONFIDENCE_FOR(score, strong),
        score,
        evidence,
      });
    }
  }

  // Strongest first, then alphabetical so the list is stable across scans of
  // an unchanged repository — a report that reshuffles between runs looks like
  // it found something new.
  out.sort((a, b) => b.score - a.score || a.name.localeCompare(b.name));
  return out;
}

/**
 * Match a signature file against the tree.
 *
 * A signature containing a slash is anchored to a path suffix (`config/routes.rb`
 * must be that path, not any file named routes.rb); a bare name matches any
 * basename at any depth. Returns the evidence string, or null.
 */
function matchPath(lowerPaths, pathSet, signature) {
  const sig = signature.toLowerCase();
  if (sig.includes("/")) {
    const hit = pathSet.has(sig) || lowerPaths.find((p) => p.endsWith("/" + sig));
    return hit ? `config: ${signature}` : null;
  }
  const hit = lowerPaths.find((p) => p === sig || p.endsWith("/" + sig));
  return hit ? `file: ${signature}` : null;
}
